mongo:
  client:
    port: ~
  database:
    name: "corobiapolitici"

logging:
  level: "INFO"
  filename: "corobiapolitici.log"

scrape:
  delay: 0.1

neo4j:
  client:
    uri: bolt://localhost:7687
    auth:
      - "neo4j"
      - "h6u4%kr"
  import_path: "/var/lib/neo4j/import/"
  temp_csv: "temp_corobiapolitici.csv"
  periodic_commit: 10000
